### ISSUE TITLE
Error when I compile for linux [Directory transcc.build not exists]

### ISSUE THREAD

**Issue by fabiuz** [KrautApps/cerberus#34]
When compiling this showed an error:
g++: error: transcc/transcc.build/cpptool/main.cpp: No such file or directory
I compared this version of Cerberus with an anterior version, this directory transcc.build exists in an anterior version but not exists in the new version.

**Comment by MikeHart66** [comment]
Sorry, I thought it was a relict from a previous build process and deleted it. I will upload it soon again.

**Comment by MikeHart66** [comment]
Reverted the deletion.
