### ISSUE TITLE
I Compile Cerberus version 2018-03-02, but After by compiling version of compiler is still anterior.

### ISSUE THREAD

**Issue by fabiuz** [KrautApps/cerberus#36]
After compiling:
Ide is version: V2018-03-02
but version of compiler transcc is still V2017-10-24.

I think there was change because of this line:
In the file VERSIONS.TXT, in the line 15:
NEW: [TRANS] Added character literals to the language.    (Author: Pixelpaladin)

**Comment by MikeHart66** [comment]
Can't you create that build yourself? I will upload it again.

**Comment by MikeHart66** [comment]
Ok, I have uploaded the new version.
