### ISSUE TITLE
Linux compile for current version

### ISSUE THREAD

**Issue by linuxfranz** [KrautApps/cerberus#38]
Hi,

I managed to compile the current Version on Opensuse Tumbleweed. There where a few errors regarding the c++ version (7.3.1) that I"ve fixed locally.

Attached patch.

Cheers
Franz

[linux_patch.txt](https://github.com/KrautApps/cerberus/files/1913022/linux_patch.txt)

**Comment by MikeHart66** [comment]
Fixed regarding the C++ version error.
